#!/usr/bin/env python3
"""
Offline pipeline: 118 track thumbnails -> centerline anchor templates.

Run from project root:
    python -m venv .venv && source .venv/bin/activate
    pip install -r tools/requirements.txt
    python tools/trace_thumbnails.py [--limit N] [--only track-12,track-15]

Outputs:
    tools/trace_output/cache/{track-id}.jpg   # downloaded thumbnails
    tools/trace_output/{track-id}_debug.png   # original + skeleton overlay
    tools/trace_output/templates.json         # extracted designs
    tools/trace_output/blacklist.txt          # IDs you exclude after review (manually edited)

After review, run again to regenerate the TS module:
    python tools/trace_thumbnails.py --emit-ts

That writes lib/track-design/auto-templates.ts which is imported by templates.ts.
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

import cv2
import networkx as nx
import numpy as np
import requests
from PIL import Image
from skimage.morphology import skeletonize

ROOT = Path(__file__).resolve().parents[1]
TRACKS_TS = ROOT / "lib" / "tracks.ts"
OUT_DIR = ROOT / "tools" / "trace_output"
CACHE_DIR = OUT_DIR / "cache"
TEMPLATES_JSON = OUT_DIR / "templates.json"
BLACKLIST = OUT_DIR / "blacklist.txt"
TS_OUT = ROOT / "lib" / "track-design" / "auto-templates.ts"

DEFAULT_STROKE_W = 0.18
DOUGLAS_PEUCKER_FRACTION = 0.015


def load_tracks() -> list[dict]:
    """Parse the lib/tracks.ts data array (assumes format generated by generate_tracks_config.py)."""
    text = TRACKS_TS.read_text(encoding="utf-8")
    pattern = re.compile(
        r'\{\s*id:\s*"([^"]+)",\s*name:\s*"([^"]+)",\s*thumbnailUrl:\s*"([^"]+)",?\s*\}',
        re.MULTILINE,
    )
    return [
        {"id": m.group(1), "name": m.group(2), "thumbnailUrl": m.group(3)}
        for m in pattern.finditer(text)
    ]


def parse_dimensions(name: str) -> tuple[float, float] | None:
    m = re.match(r"^(\d+\.?\d*)[xX×](\d+\.?\d*)", name)
    if not m:
        return None
    return float(m.group(1)), float(m.group(2))


def download(url: str, target: Path) -> bool:
    if target.exists():
        return True
    try:
        r = requests.get(url, timeout=20)
        r.raise_for_status()
        target.write_bytes(r.content)
        return True
    except Exception as e:
        print(f"  download failed: {e}", file=sys.stderr)
        return False


def trace_centerline(img_path: Path) -> np.ndarray | None:
    """Returns Nx2 array of skeleton pixel coords (col, row), or None if extraction fails."""
    img = cv2.imread(str(img_path), cv2.IMREAD_GRAYSCALE)
    if img is None:
        return None
    h, w = img.shape
    blurred = cv2.GaussianBlur(img, (5, 5), 0)
    _, binary = cv2.threshold(blurred, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    if binary.mean() > 127:
        binary = 255 - binary
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    binary = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel, iterations=2)
    binary = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel, iterations=1)

    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(binary, connectivity=8)
    if num_labels <= 1:
        return None
    largest = 1 + np.argmax(stats[1:, cv2.CC_STAT_AREA])
    mask = (labels == largest).astype(np.uint8) * 255

    skel = skeletonize(mask > 0).astype(np.uint8) * 255
    return skel


def skeleton_to_polyline(skel: np.ndarray) -> tuple[list[tuple[int, int]], bool]:
    """Convert skeleton image to ordered polyline. Returns (points, closed)."""
    pts = np.argwhere(skel > 0)
    if len(pts) < 4:
        return [], False
    g = nx.Graph()
    coord_set = {(int(r), int(c)) for r, c in pts}
    for r, c in pts:
        for dr in (-1, 0, 1):
            for dc in (-1, 0, 1):
                if dr == 0 and dc == 0:
                    continue
                nb = (int(r) + dr, int(c) + dc)
                if nb in coord_set:
                    g.add_edge((int(r), int(c)), nb, weight=np.hypot(dr, dc))

    # Strip short branch spurs
    pruned = True
    while pruned:
        pruned = False
        for node in list(g.nodes):
            if g.degree(node) == 1:
                # walk the spur
                cur = node
                length = 0.0
                visited = []
                while g.degree(cur) <= 2:
                    visited.append(cur)
                    nbrs = [n for n in g.neighbors(cur) if n not in visited]
                    if not nbrs:
                        break
                    length += g[cur][nbrs[0]]["weight"]
                    cur = nbrs[0]
                    if length > 15:
                        break
                if length <= 15:
                    g.remove_nodes_from(visited)
                    pruned = True

    if g.number_of_nodes() < 4:
        return [], False

    # Detect cycle
    try:
        cycle = nx.find_cycle(g)
        nodes = [edge[0] for edge in cycle]
        return [(c, r) for r, c in nodes], True
    except nx.NetworkXNoCycle:
        pass

    # Open: longest shortest path
    if not nx.is_connected(g):
        components = list(nx.connected_components(g))
        sub = max(components, key=len)
        g = g.subgraph(sub).copy()

    nodes = list(g.nodes)
    best_path: list = []
    for source in nodes[:: max(1, len(nodes) // 30)]:
        lengths = nx.single_source_dijkstra_path_length(g, source)
        far = max(lengths, key=lengths.get)
        path = nx.shortest_path(g, source, far)
        if len(path) > len(best_path):
            best_path = path
    return [(c, r) for r, c in best_path], False


def douglas_peucker(points: list[tuple[float, float]], epsilon: float) -> list[tuple[float, float]]:
    if len(points) < 3:
        return points
    arr = np.array(points, dtype=float)
    contour = arr.reshape(-1, 1, 2).astype(np.float32)
    simplified = cv2.approxPolyDP(contour, epsilon, closed=False)
    return [(float(p[0][0]), float(p[0][1])) for p in simplified]


def to_design(
    pixel_points: list[tuple[float, float]],
    closed: bool,
    img_w: int,
    img_h: int,
    bbox_w: float,
    bbox_h: float,
    template_id: str,
) -> dict:
    sx = bbox_w / img_w
    sy = bbox_h / img_h
    s = min(sx, sy)
    off_x = (bbox_w - img_w * s) / 2
    off_y = (bbox_h - img_h * s) / 2
    anchors = []
    for i, (x, y) in enumerate(pixel_points):
        anchors.append(
            {
                "id": f"a{i}",
                "x": round(x * s + off_x, 4),
                "y": round(y * s + off_y, 4),
                "r": round(DEFAULT_STROKE_W * 1.5, 4),
            }
        )
    return {
        "version": 1,
        "bboxW": bbox_w,
        "bboxH": bbox_h,
        "strokeW": DEFAULT_STROKE_W,
        "closed": closed,
        "anchors": anchors,
        "templateId": template_id,
    }


def write_debug(img_path: Path, points: list[tuple[float, float]], closed: bool, out_path: Path):
    img = cv2.imread(str(img_path))
    if img is None:
        return
    if len(points) >= 2:
        pts = np.array([[int(round(x)), int(round(y))] for x, y in points], dtype=np.int32)
        cv2.polylines(img, [pts], isClosed=closed, color=(0, 0, 255), thickness=2)
        for x, y in points:
            cv2.circle(img, (int(round(x)), int(round(y))), 4, (255, 80, 0), -1)
    cv2.imwrite(str(out_path), img)


def emit_ts():
    if not TEMPLATES_JSON.exists():
        print("no templates.json yet", file=sys.stderr)
        return
    data = json.loads(TEMPLATES_JSON.read_text())
    blacklist = set()
    if BLACKLIST.exists():
        blacklist = {l.strip() for l in BLACKLIST.read_text().splitlines() if l.strip() and not l.startswith("#")}
    kept = {k: v for k, v in data.items() if k not in blacklist}
    body = json.dumps(kept, indent=2, ensure_ascii=False)
    TS_OUT.write_text(
        '// AUTO-GENERATED by tools/trace_thumbnails.py — do not edit by hand\n'
        'import { TrackDesign } from "./types"\n\n'
        f'export const autoTemplates: Record<string, TrackDesign & {{ sourceTrackId: string }}> = {body} as const\n'
    )
    print(f"wrote {TS_OUT} ({len(kept)} templates, {len(blacklist)} blacklisted)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--only", type=str, default=None, help="comma-separated track IDs")
    ap.add_argument("--emit-ts", action="store_true", help="just regenerate the TS module from existing JSON")
    args = ap.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    if args.emit_ts:
        emit_ts()
        return

    tracks = load_tracks()
    if args.only:
        whitelist = set(args.only.split(","))
        tracks = [t for t in tracks if t["id"] in whitelist]
    if args.limit:
        tracks = tracks[: args.limit]

    results: dict[str, dict] = {}
    if TEMPLATES_JSON.exists():
        results = json.loads(TEMPLATES_JSON.read_text())

    for i, t in enumerate(tracks):
        print(f"[{i+1}/{len(tracks)}] {t['id']} {t['name']}")
        dims = parse_dimensions(t["name"])
        if dims is None:
            print("  no dimensions in name, skipping")
            continue
        bbox_w, bbox_h = dims
        local = CACHE_DIR / f"{t['id']}.jpg"
        if not download(t["thumbnailUrl"], local):
            continue
        skel = trace_centerline(local)
        if skel is None:
            print("  centerline extraction failed")
            continue
        polyline, closed = skeleton_to_polyline(skel)
        if len(polyline) < 4:
            print("  polyline too short")
            continue
        img = cv2.imread(str(local), cv2.IMREAD_GRAYSCALE)
        h, w = img.shape
        eps = max(w, h) * DOUGLAS_PEUCKER_FRACTION
        simplified = douglas_peucker(polyline, eps)
        if len(simplified) < (3 if closed else 2):
            print("  too few anchors after simplification")
            continue
        design = to_design(simplified, closed, w, h, bbox_w, bbox_h, t["id"])
        results[t["id"]] = design
        debug_path = OUT_DIR / f"{t['id']}_debug.png"
        write_debug(local, simplified, closed, debug_path)
        print(f"  ok: {len(simplified)} anchors, {'closed' if closed else 'open'}")

    TEMPLATES_JSON.write_text(json.dumps(results, indent=2, ensure_ascii=False))
    print(f"\n{TEMPLATES_JSON} updated ({len(results)} templates)")
    print(f"Review {OUT_DIR}/*.png and add bad IDs to {BLACKLIST}, then run with --emit-ts")


if __name__ == "__main__":
    main()
